### PR TITLE
changed copyright financial details;

### PR DESCRIPTION
**Pull request by DrBeepBoop**
changed readme to add more party

### CODE REVIEW

**Comment by AdmiralPotato** [comment]
Sorry, the financial details need to be consistent in the copyright. You have one that says $500, and another that says $5. Please make them consistent.

**Review by AdmiralPotato — CHANGES_REQUESTED** [review]
Please fix the pricing to be consistent

**Comment by DrBeepBoop** [comment]
Updated; awaiting feedback

**Review by AdmiralPotato — APPROVED** [review]
Looks good

**Pull request merged**
